site_name: MOOCABP
nav:
- 1. Inicio: 'README.md'
- 2. Prototipo: 'Prototipo.md'
- 3. EvaluaciónABP: 'EvaluaciónABP.md'
- About:
    - 'Licencia': 'licencia.md'


##theme: 'windmill'
##theme: 'cinder'
## theme: 'rtd-dropdown'
theme:
  name: 'material'
  language: 'es'

markdown_extensions:
  - admonition
  - codehilite